 List<String> agencyList = [
    '21 Century',
    '360 Property Network',
    '3 Star Real Estate',
    '4 Walls Network Builders & Contractors',
    'A.Z Estate',
    'AB ENTERPRISES',
    'Abdullah Estate',
    'Al Jadeed Properties',
    'Al Kabeer Associates',
    'Al Moiz Enterprise',
    'Alpha Land',
    'Arfat Estate & Marketing',
    'Basit Associates',
     'A.Z Estate',
    'AB ENTERPRISES',
    'Abdullah Estate',
    'Al Jadeed Properties',
    'Bin Aziz Associates ',
     '21 Century',
    '360 Property Network',
    '3 Star Real Estate',
    '4 Wall',
     'AB ENTERPRISES',
    'Abdullah Estate',
    'Al Jadeed Properties',
    'Bin Aziz Associates ',
     '21 Century',

  ];